// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: protos/scrape.proto

package scrapepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScrapeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ScrapeRequest) Reset() {
	*x = ScrapeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_scrape_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeRequest) ProtoMessage() {}

func (x *ScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_scrape_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeRequest.ProtoReflect.Descriptor instead.
func (*ScrapeRequest) Descriptor() ([]byte, []int) {
	return file_protos_scrape_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ScrapeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dealer string `protobuf:"bytes,1,opt,name=dealer,proto3" json:"dealer,omitempty"`
	Price  int64  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_scrape_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_scrape_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_protos_scrape_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeResponse) GetDealer() string {
	if x != nil {
		return x.Dealer
	}
	return ""
}

func (x *ScrapeResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_protos_scrape_proto protoreflect.FileDescriptor

var file_protos_scrape_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x22, 0x23, 0x0a,
	0x0d, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x32, 0x4a, 0x0a, 0x0d, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x12, 0x15, 0x2e,
	0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x2e, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x2e, 0x53, 0x63,
	0x72, 0x61, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a,
	0x5a, 0x18, 0x2e, 0x2f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_scrape_proto_rawDescOnce sync.Once
	file_protos_scrape_proto_rawDescData = file_protos_scrape_proto_rawDesc
)

func file_protos_scrape_proto_rawDescGZIP() []byte {
	file_protos_scrape_proto_rawDescOnce.Do(func() {
		file_protos_scrape_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_scrape_proto_rawDescData)
	})
	return file_protos_scrape_proto_rawDescData
}

var file_protos_scrape_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_scrape_proto_goTypes = []interface{}{
	(*ScrapeRequest)(nil),  // 0: scrape.ScrapeRequest
	(*ScrapeResponse)(nil), // 1: scrape.ScrapeResponse
}
var file_protos_scrape_proto_depIdxs = []int32{
	0, // 0: scrape.ScrapeService.Scrape:input_type -> scrape.ScrapeRequest
	1, // 1: scrape.ScrapeService.Scrape:output_type -> scrape.ScrapeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_scrape_proto_init() }
func file_protos_scrape_proto_init() {
	if File_protos_scrape_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_scrape_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrapeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_scrape_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScrapeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_scrape_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_scrape_proto_goTypes,
		DependencyIndexes: file_protos_scrape_proto_depIdxs,
		MessageInfos:      file_protos_scrape_proto_msgTypes,
	}.Build()
	File_protos_scrape_proto = out.File
	file_protos_scrape_proto_rawDesc = nil
	file_protos_scrape_proto_goTypes = nil
	file_protos_scrape_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ScrapeServiceClient is the client API for ScrapeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScrapeServiceClient interface {
	Scrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (*ScrapeResponse, error)
}

type scrapeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScrapeServiceClient(cc grpc.ClientConnInterface) ScrapeServiceClient {
	return &scrapeServiceClient{cc}
}

func (c *scrapeServiceClient) Scrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (*ScrapeResponse, error) {
	out := new(ScrapeResponse)
	err := c.cc.Invoke(ctx, "/scrape.ScrapeService/Scrape", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScrapeServiceServer is the server API for ScrapeService service.
type ScrapeServiceServer interface {
	Scrape(context.Context, *ScrapeRequest) (*ScrapeResponse, error)
}

// UnimplementedScrapeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedScrapeServiceServer struct {
}

func (*UnimplementedScrapeServiceServer) Scrape(context.Context, *ScrapeRequest) (*ScrapeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scrape not implemented")
}

func RegisterScrapeServiceServer(s *grpc.Server, srv ScrapeServiceServer) {
	s.RegisterService(&_ScrapeService_serviceDesc, srv)
}

func _ScrapeService_Scrape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapeServiceServer).Scrape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scrape.ScrapeService/Scrape",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapeServiceServer).Scrape(ctx, req.(*ScrapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ScrapeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scrape.ScrapeService",
	HandlerType: (*ScrapeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scrape",
			Handler:    _ScrapeService_Scrape_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/scrape.proto",
}
