# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scrape.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scrape.proto',
  package='scrape',
  syntax='proto3',
  serialized_options=b'Z\030./scrape_server/scrapepb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cscrape.proto\x12\x06scrape\"\x1d\n\rScrapeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"/\n\x0eScrapeResponse\x12\x0e\n\x06\x64\x65\x61ler\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x03\x32J\n\rScrapeService\x12\x39\n\x06Scrape\x12\x15.scrape.ScrapeRequest\x1a\x16.scrape.ScrapeResponse\"\x00\x42\x1aZ\x18./scrape_server/scrapepbb\x06proto3'
)




_SCRAPEREQUEST = _descriptor.Descriptor(
  name='ScrapeRequest',
  full_name='scrape.ScrapeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='scrape.ScrapeRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=53,
)


_SCRAPERESPONSE = _descriptor.Descriptor(
  name='ScrapeResponse',
  full_name='scrape.ScrapeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dealer', full_name='scrape.ScrapeResponse.dealer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='scrape.ScrapeResponse.price', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['ScrapeRequest'] = _SCRAPEREQUEST
DESCRIPTOR.message_types_by_name['ScrapeResponse'] = _SCRAPERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScrapeRequest = _reflection.GeneratedProtocolMessageType('ScrapeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPEREQUEST,
  '__module__' : 'scrape_pb2'
  # @@protoc_insertion_point(class_scope:scrape.ScrapeRequest)
  })
_sym_db.RegisterMessage(ScrapeRequest)

ScrapeResponse = _reflection.GeneratedProtocolMessageType('ScrapeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPERESPONSE,
  '__module__' : 'scrape_pb2'
  # @@protoc_insertion_point(class_scope:scrape.ScrapeResponse)
  })
_sym_db.RegisterMessage(ScrapeResponse)


DESCRIPTOR._options = None

_SCRAPESERVICE = _descriptor.ServiceDescriptor(
  name='ScrapeService',
  full_name='scrape.ScrapeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=104,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='Scrape',
    full_name='scrape.ScrapeService.Scrape',
    index=0,
    containing_service=None,
    input_type=_SCRAPEREQUEST,
    output_type=_SCRAPERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCRAPESERVICE)

DESCRIPTOR.services_by_name['ScrapeService'] = _SCRAPESERVICE

# @@protoc_insertion_point(module_scope)
